### ISSUE TITLE
Replace FTP sync with wifi sync

### ISSUE THREAD

**Issue by stevenbird** [aikuma/aikuma#386]
Now that Aikuma has an embedded webserver, we can set up any phone as a wifi hotspot and others can sync files over wifi.

**Comment by stevenbird** [comment]
Drop FTP sync, once #401 is implemented.

**Comment by stevenbird** [comment]
We should consider peer-to-peer as well.

**Comment by Lingomat** [comment]
This is very interesting. Suppose one participant cycles to a village with a number of phones. We may have the phones sychronised when they take them but when participants work in a village, they cannot actually collaborate on tasks until the files share between phones.

The current model(s) assume connecting to one server type devices, a WiFi access point. That's okay but it introduces some restrictions. One device must be set up differently from the others. This device must be within WiFi range of *all* other devices, and must be charged and running. This is doable but suggests further training.

Peer-to-peer WiFi suggests that files propagate across an entire network so long as any device is in range of any other device. No device is set up different from any others.

It seems this is reasonably well supported in Android post 4.0:
http://developer.android.com/guide/topics/connectivity/wifip2p.html

Assuming this were to work ideally; one could take any device, connect it to a WAN for cloud synchronisation, and then just disconnect and let the peer-to-peer sync all the other devices.

This makes me also wonder... WiFi range on mobile phones is reasonably largely because there are high gain antennas on access points. The gain on the internal antennas is very small. The range will be impacted. I will assess to what extent.

**Comment by stevenbird** [comment]
It would be fine to avoid the embedded webserver and wifi hotspot; peer-to-peer would be simpler.

**Comment by stevenbird** [comment]
We are going ahead with wifip2p. This involves pairs of phones, not a hub-and-spoke model.

**Comment by stevenbird** [comment]
After sync is complete, display storage statistics (the same ones displayed in the about screen).
